modLoader = "javafml"
loaderVersion = "[34,)"
issueTrackerURL = "https://github.com/cofh/feedback"
license = "CoFH - Don't Be A Jerk (Learn, Don't Steal)"

[[mods]]
modId = "redstone_arsenal"
version = "${file.jarVersion}"
displayName = "Redstone Arsenal"
updateJSONURL = "https://raw.github.com/cofh/version/master/redstone_arsenal/update.json"
displayURL = "https://teamcofh.com/"
logoFile = "logo.png"
credits = "Team CoFH"
authors = "King Lemming"
description = '''
Redstone Arsenal!
'''
[[dependencies.redstone_arsenal]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.redstone_arsenal]]
modId = "forge"
mandatory = true
versionRange = "[36.2.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.redstone_arsenal]]
modId = "cofh_core"
mandatory = true
versionRange = "[1.3,1.4]"
ordering = "AFTER"
side = "BOTH"